import { decodeMap } from "./utils";

export const level = decodeMap(
  "AAoACoYQMhggYQMhhAyBMBYFQwgTAWBUMIEwKgNCiAyA0LIDQogNASA0DIDQMgNDCA0HIDQEgNDCAyA0MIDQcgNASAkDICQMgJDCAkHICQEgJDCAyA0LIDQogNASAkMIEQHgXDCBEB4FwEgJDSGEGIMQ0gxDCDEBIEQHgPAeA8B4DwHgPAs",
);
